import os
import sys

MAIN_PATH = os.path.abspath(os.path.join(__file__, "..", ".."))
CURRENT_WORKING_FILE_DIRECTORY = os.path.abspath(os.path.join(__file__))
CURRENT_WORKING_DIRECTORY = os.path.abspath(os.path.join(__file__, ".."))

if MAIN_PATH not in sys.path:
    sys.path.append(MAIN_PATH)

dir_path = os.path.dirname(os.path.realpath(__file__))
for root, dirs, files in os.walk(dir_path):
    sys.path.append(root)


def defualt_properties_info():
    """
    Default Properties are added here
    """
    pass

"""
Model/name/colour and other properties of Ego vehicle
"""
DEFAULT_EGO_PROPERTIES = {"model": "simonedriver",
                          "category": "Ego",
                          "name": "SimOne Driver",
                          "obuId": "0",
                          "obu_enabled": "false",
                          "color": "#63BA3C"}


"""
Model/name/colour and other properties of objects
"""
DEFAULT_OBJ_PROPERTIES = {
            'car': {'Obj1':{
                    "asset_id": "1000064",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "ENCAP_GVT01",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "ENCAP_GVT01",
                     "obuId": "1",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},
                'Obj2':{
                    "asset_id": "1000017",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "019-ChevroletCamaro",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "Chevrolet Camaro",
                     "obuId": "2",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},
                'Obj3':{
                    "asset_id": "1000004",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "005-AudiA8",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "AudiA8",
                     "obuId": "3",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},
                'Obj4':{
                    "asset_id": "1000008",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "009-Audi TT",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "Audi TT",
                     "obuId": "4",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},
                'Obj5':{
                    "asset_id": "1000009",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "010-BentleyContinentalGT",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "Bentley Continental GT",
                     "obuId": "5",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},
                'Obj6':{
                    "asset_id": "1000021",
                     "builtIn": "true",
                     "resource_type": "builtIn",
                     "semantic_type": "vehicle",
                     "model": "023-Ferrari458",
                     "category": "vehicle",
                     "subCategory": "car",
                     "name": "Ferrari 458",
                     "obuId": "6",
                     "obu_enabled": "true",
                     "scaleX": "1",
                     "scaleY": "1",
                     "scaleZ": "1",
                     "color": "#FF0000"},

},

            'bicycle' : {'Obj1':{"asset_id": "1200001",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Bike01",
                                 "category": "bicycle",
                                 "subCategory": "bicycle",
                                 "name": "Bike01",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj2':{"asset_id": "1200005",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Bike05",
                                 "category": "bicycle",
                                 "subCategory": "bicycle",
                                 "name": "Bike05",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj3':{"asset_id": "1200002",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Bike02",
                                 "category": "bicycle",
                                 "subCategory": "bicycle",
                                 "name": "Bike02",
                                 "obuId": "3",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj4':{"asset_id": "1200003",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Bike03",
                                 "category": "bicycle",
                                 "subCategory": "bicycle",
                                 "name": "Bike03",
                                 "obuId": "4",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj5':{"asset_id": "1200006",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Bike06",
                                 "category": "bicycle",
                                 "subCategory": "bicycle",
                                 "name": "Bike06",
                                 "obuId": "5",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                    },
            'human' : {'Obj1' :{"asset_id": "1100000",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Ped00",
                                 "category": "pedestrian",
                                 "subCategory": "pedestrian",
                                 "name": "Ped00",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                       'Obj2' : {"asset_id": "1100003",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Ped03",
                                 "category": "pedestrian",
                                 "subCategory": "pedestrian",
                                 "name": "Ped03",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                       'Obj3' : {"asset_id": "1100008",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Ped08",
                                 "category": "pedestrian",
                                 "subCategory": "pedestrian",
                                 "name": "Ped08",
                                 "obuId": "3",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                       },
            'Truck' : {'Obj1' : {"asset_id": "1000054",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "057-VanTruck02",
                                 "category": "vehicle",
                                 "subCategory": "truck",
                                 "name": "Van Truck 02",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj2' : {"asset_id": "1000053",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "056-VanTruck01",
                                 "category": "vehicle",
                                 "subCategory": "truck",
                                 "name": "Van Truck 01",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj3' : {"asset_id": "1000049",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "vehicle",
                                 "model": "052-Truck03",
                                 "category": "vehicle",
                                 "subCategory": "vehicle",
                                 "name": "Truck 03",
                                 "obuId": "3",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                    },
            'twowheelers' : {'Obj1' : {"asset_id": "1000057",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Motorcycle03",
                                 "category": "vehicle",
                                 "subCategory": "motorbike",
                                 "name": "Motorcycle03",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj2' : {"asset_id": "1000058",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "Motorcycle02",
                                 "category": "vehicle",
                                 "subCategory": "motorbike",
                                 "name": "Motorcycle02",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                    },
            'pole' : {'Obj1' : {"asset_id": "2900057",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "DefacedSign02",
                                 "category": "static",
                                 "subCategory": "defacedsign",
                                 "name": "Defaced Sign 02",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj2' : {"asset_id": "2900058",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "DefacedSign03",
                                 "category": "static",
                                 "subCategory": "defacedsign",
                                 "name": "Defaced Sign 03",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj3' : {"asset_id": "2900065",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "DefacedSign09",
                                 "category": "static",
                                 "subCategory": "defacedsign",
                                 "name": "Defaced Sign 09",
                                 "obuId": "3",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                      },

            'obstacle' : {'Obj1' : {"asset_id": "2900006",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_11",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Traffic Cone 01",
                                 "obuId": "1",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj2' : {"asset_id": "2900007",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_16",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Traffic Cone 02",
                                 "obuId": "2",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj3' : {"asset_id": "2900008",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_18",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Road Block 01",
                                 "obuId": "3",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj4' : {"asset_id": "2900004",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_07",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Plastic Barrier 01",
                                 "obuId": "4",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj5' : {"asset_id": "2900005",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_10",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Plastic Barrier 02",
                                 "obuId": "5",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj6' : {"asset_id": "2900014",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_TroubleSign_01",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Warning Triangle 01",
                                 "obuId": "6",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj7' : {"asset_id": "2900009",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_25",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Road Block 02",
                                 "obuId": "7",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"},
                    'Obj8' : {"asset_id": "29000010",
                                 "builtIn": "true",
                                 "resource_type": "builtIn",
                                 "semantic_type": "none",
                                 "model": "SM_PRO_Block_61",
                                 "category": "static",
                                 "subCategory": "roadblock",
                                 "name": "Barricade 02",
                                 "obuId": "8",
                                 "obu_enabled": "false",
                                 "scaleX": "1",
                                 "scaleY": "1",
                                 "scaleZ": "1"}
                     }
                }



"""
Size properties of any vehicle or object
"""
DEFAULT_SIZE_PROPERTIES = {
        'car': {'width': 1.73, 'length': 4.03, 'height': 1.43},
        'van': {'width': 2.0, 'length': 5.0, 'height': 2.0},
        'truck': {'width': 2.3, 'length': 4.3, 'height': 2.6},
        'trailer': {'width': 2.5, 'length': 12.0, 'height': 4.0},
        'semitrailer': {'width': 2.5, 'length': 14.0, 'height': 4.0},
        'bus': {'width': 2.5, 'length': 12.0, 'height': 3.5},
        'twowheelers': {'width': 0.82, 'length': 1.99, 'height': 1.77},
        'bicycle': {'width': 0.72, 'length': 1.87, 'height': 1.97},
        'train': {'width': 3.0, 'length': 20.0, 'height': 4.0},
        'tram': {'width': 2.5, 'length': 20.0, 'height': 3.5},
        'human': {'width': 0.18, 'length': 0.59, 'height': 1.82},
        'wheelchair': {'width': 0.7, 'length': 1.2, 'height': 1.5},
        'animal': {'width': 0.5, 'length': 1.5, 'height': 1.5},
        'roadsideobjects' : {'width': 0.66, 'length': 1.54, 'height': 0.99},
        'trafficsign' : {'width': 1.26, 'length': 1.18, 'height': 10.25}
    }

